name: smiles-rnn
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.2
  - pip
  - pip:
    - torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cu116
    - tqdm
    - deepsmiles
    - selfies
    - promptsmiles
    - molscore<2
    - rdkit
    - numpy
    - tensorboard